// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pq-c1-test/pkg/models/shared"
)

type C1APITaskV1TaskServiceCreateGrantTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APITaskV1TaskServiceCreateGrantResponse *shared.C1APITaskV1TaskServiceCreateGrantResponse
}
