// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pq-c1-test/pkg/models/shared"
)

type C1APIAuthV1AuthIntrospectResponse struct {
	ContentType string
	// Succesful response
	IntrospectResponse *shared.IntrospectResponse
	StatusCode         int
	RawResponse        *http.Response
}
