// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pq-c1-test/pkg/models/shared"
)

type C1APITaskV1TaskActionsServiceDenyRequest struct {
	TaskID                                        string                                                `pathParam:"style=simple,explode=false,name=task_id"`
	C1APITaskV1TaskActionsServiceDenyRequestInput *shared.C1APITaskV1TaskActionsServiceDenyRequestInput `request:"mediaType=application/json"`
}

type C1APITaskV1TaskActionsServiceDenyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APITaskV1TaskActionsServiceDenyResponse *shared.C1APITaskV1TaskActionsServiceDenyResponse
}
