// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pq-c1-test/pkg/models/shared"
)

type C1APITaskV1TaskActionsServiceCommentRequest struct {
	TaskID                                           string                                                   `pathParam:"style=simple,explode=false,name=task_id"`
	C1APITaskV1TaskActionsServiceCommentRequestInput *shared.C1APITaskV1TaskActionsServiceCommentRequestInput `request:"mediaType=application/json"`
}

type C1APITaskV1TaskActionsServiceCommentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APITaskV1TaskActionsServiceCommentResponse *shared.C1APITaskV1TaskActionsServiceCommentResponse
}
