// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pq-c1-test/pkg/models/shared"
)

type C1APIAppV1AppResourceTypeServiceGetRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=app_id"`
	ID    string `pathParam:"style=simple,explode=false,name=id"`
}

type C1APIAppV1AppResourceTypeServiceGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APIAppV1AppResourceTypeServiceGetResponse *shared.C1APIAppV1AppResourceTypeServiceGetResponse
}
