// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"pq-c1-test/pkg/models/shared"
)

type C1APITaskV1TaskActionsServiceApproveRequest struct {
	TaskID                                           string                                                   `pathParam:"style=simple,explode=false,name=task_id"`
	C1APITaskV1TaskActionsServiceApproveRequestInput *shared.C1APITaskV1TaskActionsServiceApproveRequestInput `request:"mediaType=application/json"`
}

type C1APITaskV1TaskActionsServiceApproveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	C1APITaskV1TaskActionsServiceApproveResponse *shared.C1APITaskV1TaskActionsServiceApproveResponse
}
