// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskSearchResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type C1APITaskV1TaskSearchResponseExpanded struct {
	// The type of the serialized message.
	AtType *string `json:"@type,omitempty"`
}

// C1APITaskV1TaskSearchResponse - The TaskSearchResponse message.
type C1APITaskV1TaskSearchResponse struct {
	// The expanded field.
	Expanded []C1APITaskV1TaskSearchResponseExpanded `json:"expanded,omitempty"`
	// The list field.
	List []C1APITaskV1TaskView `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}
