// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APIAppV1GetAppEntitlementResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type C1APIAppV1GetAppEntitlementResponseExpanded struct {
	// The type of the serialized message.
	AtType *string `json:"@type,omitempty"`
}

// C1APIAppV1GetAppEntitlementResponse - The GetAppEntitlementResponse message.
type C1APIAppV1GetAppEntitlementResponse struct {
	// The AppEntitlementView message.
	AppEntitlementView *C1APIAppV1AppEntitlementView `json:"appEntitlementView,omitempty"`
	// The expanded field.
	Expanded []C1APIAppV1GetAppEntitlementResponseExpanded `json:"expanded,omitempty"`
}
