// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskActionsServiceApproveResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type C1APITaskV1TaskActionsServiceApproveResponseExpanded struct {
	// The type of the serialized message.
	AtType *string `json:"@type,omitempty"`
}

// C1APITaskV1TaskActionsServiceApproveResponse - The TaskActionsServiceApproveResponse message.
type C1APITaskV1TaskActionsServiceApproveResponse struct {
	// The expanded field.
	Expanded []C1APITaskV1TaskActionsServiceApproveResponseExpanded `json:"expanded,omitempty"`
	// The TaskView message.
	TaskView *C1APITaskV1TaskView `json:"taskView,omitempty"`
}
