// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// C1APITaskV1TaskServiceCreateGrantResponseExpanded - Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type C1APITaskV1TaskServiceCreateGrantResponseExpanded struct {
	// The type of the serialized message.
	AtType *string `json:"@type,omitempty"`
}

// C1APITaskV1TaskServiceCreateGrantResponse - The TaskServiceCreateGrantResponse message.
type C1APITaskV1TaskServiceCreateGrantResponse struct {
	// The expanded field.
	Expanded []C1APITaskV1TaskServiceCreateGrantResponseExpanded `json:"expanded,omitempty"`
	// The TaskView message.
	TaskView *C1APITaskV1TaskView `json:"taskView,omitempty"`
}
