// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserView - The UserView message.
type UserView struct {
	DelegatedUserPath *string `json:"delegatedUserPath,omitempty"`
	DirectoriesPath   *string `json:"directoriesPath,omitempty"`
	ManagersPath      *string `json:"managersPath,omitempty"`
	RolesPath         *string `json:"rolesPath,omitempty"`
	// The User message.
	User *User `json:"user,omitempty"`
}
