// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserAttributeMappingSource - The UserAttributeMappingSource message.
type UserAttributeMappingSource struct {
	AppID                      *string `json:"appId,omitempty"`
	AppUserID                  *string `json:"appUserId,omitempty"`
	AppUserProfileAttributeKey *string `json:"appUserProfileAttributeKey,omitempty"`
	UserAttributeMappingID     *string `json:"userAttributeMappingId,omitempty"`
	Value                      *string `json:"value,omitempty"`
}
